[phases.setup]
nixPkgs = ["python312", "gcc", "libffi", "python312Packages.pip", "python312Packages.setuptools", "python312Packages.wheel"]

[phases.install]
cmds = ["python3 -m pip install -r backend/requirements.txt"]

[app]
run = "cd backend && python3 main.py"
